#!/bin/sh
#
# install apps using local versions of glib
# into home directory
#
# This version setup for x86_64 full 64-bit
# Remove "64" anywhere below for a 32-bit build.
 
LOCAL_HOME=$HOME
 
export PATH=$LOCAL_HOME/bin:$PATH
 
# I try not to maintain my own gcc, but sometimes you gotta :
# export CC="$LOCAL_HOME/bin/gcc"
# export GCC=$CC
 
export CPPFLAGS="-I$LOCAL_HOME/include -I/usr/X11R6/include $CPPFLAGS"
export CFLAGS="-I$LOCAL_HOME/include -I/usr/X11R6/include $CFLAGS"
export CXXFLAGS="-I$LOCAL_HOME/include -I/usr/X11R6/include  $CXXFLAGS"
export LDFLAGS="-L$LOCAL_HOME/lib -L/usr/lib64 -L/usr/X11R6/lib64 $LDFLAGS"
export PKG_CONFIG=$LOCAL_HOME/bin/pkg-config
export PKG_CONFIG_PATH="$LOCAL_HOME/lib/pkgconfig:/usr/lib64/pkgconfig:$PKG_CONFIG_PATH"
export LD_LIBRARY_PATH="$LOCAL_HOME/lib:/usr/X11R6/lib64:/usr/lib64"
#export ACLOCAL_FLAGS="-I /home/maxb/share/aclocal"
 
./configure --prefix=$LOCAL_HOME \
  --x-includes=/usr/X11R6/include \
  --x-libraries=/usr/X11R6/lib "$@"
